PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX dco: <http://info.deepcarbon.net/schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX vitro-public: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bibo: <http://purl.org/ontology/bibo/>

SELECT DISTINCT ?title ?dcoId ?mostSpecificType ?isDcoPublication ?doi ?publicationYear ?community ?communityName ?venue ?venueName ?event ?eventName ?abstract ?subjectArea ?subjectAreaLabel
WHERE {
  {publication} rdfs:label ?label .
  BIND(str(?label) AS ?title) .
  OPTIONAL { {publication} dco:isContributionToDCO ?isDcoPublication . }
  OPTIONAL { {publication} vitro:mostSpecificType [ rdfs:label ?mst ] . BIND(str(?mst) AS ?mostSpecificType) . }
  OPTIONAL { {publication} dco:hasDcoId ?dcoId . }
  OPTIONAL { {publication} dco:yearOfPublication ?publicationYear . }
  OPTIONAL { {publication} dco:associatedDCOCommunity ?community . ?community rdfs:label ?clbl . BIND(str(?clbl) AS ?communityName) . }
  OPTIONAL { {publication} bibo:presentedAt ?event . ?event rdfs:label ?elbl . BIND(str(?elbl) AS ?eventName) . }
  OPTIONAL { {publication} vivo:hasPublicationVenue ?venue . ?venue rdfs:label ?vlbl . BIND(str(?vlbl) AS ?venueName) . }
  OPTIONAL { {publication} bibo:abstract ?abstract . }
  OPTIONAL { {publication} vivo:hasSubjectArea ?subjectArea . ?subjectArea rdfs:label ?salbl . BIND(str(?salbl) AS ?subjectAreaLabel) . }
  OPTIONAL { {publication} bibo:doi ?doi_str . BIND(str(?doi_str) AS ?doi) . }
}
